Shorthand for IS_BUILD_MODE
denoland/fresh pull request #2268
Opened 2024-01-19 16:16 UTC by mcgear

This is a quick shorthand for IS_BUILD_MODE (Deno.args.includes("build")), should help simplify code that needs to not run during ahead of time builds. Will address #2240 .

2024-01-26 04:42 UTC, deer requested changes
My standard comment: tests?

Although you could probably get away in this case without writing anything new if you just refactor the one place in the codebase that uses this line to use your new `const`:
https://github.com/denoland/fresh/blob/34c875c71cc5c25a1e355bee6fcdf798099f38a9/src/dev/dev_command.ts#L41

This is executed in the tests, so if it works here, I'd say it's covered.

2024-01-28 08:01 UTC, mcgear commented
This change has been put in place. Thanks for the thoughts.

2024-01-28 09:48 UTC, deer approved these changes

2024-01-31 18:04 UTC, mcgear commented
Just updated the branch

2026-03-26 15:29 UTC, bartlomieju commented
Thanks for the contribution! This PR is from the Fresh 1.x era. The files modified here (`src/dev/dev_command.ts`, `src/server/mod.ts`, `src/server/utils.ts`) no longer exist in Fresh 2.x. The build mode distinction is now handled via `config.mode`.

Closing as stale.

2026-03-26 15:29 UTC, closed without merging